spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./data/db_test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # 실행 시 테이블 생성, 종료 시 삭제 (테스트 환경)
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always  # data.sql 실행 허용
  logging:
    level:
      root: debug  # 전체 애플리케이션 로그 레벨을 info로 설정
      com.tripmarket: debug  # 패키지별 로깅 (서비스 코드에서 로그가 찍히도록)

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json