logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web: DEBUG
server:
  port: 8080

spring:
  profiles:
    include: secret
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    # url: jdbc:h2:mem:tripmarket;MODE=MYSQL
    url: jdbc:h2:./backend/db/tripmarket;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    # ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/chatdb?authSource=admin
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    dynamic: true
    host: "localhost"
    port: 5672
    virtual-host: "/"
    username: "guest"
    password: "guest"
    chat:
      queue:
        name: "chat.queue"
      exchange:
        name: "chat.exchange"
      routing:
        key: "*.room."
    relay:
      port: 61613
      system-login: guest
      system-passcode: guest
      client-login: guest
      client-passcode: guest
    listener:
      simple:
        auto-startup: true
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
